apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-module.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ml-module.labels" . | nindent 4 }}
spec:
  type: ClusterIP       # interne au cluster uniquement
                        # pas d'accès externe : ce service parle Kafka, pas HTTP
  selector:
    {{- include "ml-module.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
