image:
  repository: ghcr.io/farid841/pre_processing-container-generator-from-mlflow/model-ztf-real-bogus
  tag: v55257832-55257832
  pullPolicy: IfNotPresent

module:
  name: ztf-real-bogus
  version: v55257832
  componentType: model
  mode: streaming

kafka:
  bootstrapServers: "172.18.90.239:29092"
  inputTopic: fink-ztf-real-bogus-preprocessed
  outputTopic: fink-ztf-real-bogus-results
  consumerGroupId: ztf-real-bogus-model-streaming

# MLflow scoring server runs on 8080 with /ping (not 8000 with /health)
api:
  port: 8080
  host: "0.0.0.0"
  healthPath: "/ping"
