title: MLflow x Fink Quickstart
author: Farid
logo: ""

repository:
  url: https://github.com/Farid841/pre_processing-container-generator-from-mlflow
  branch: main
  path_to_book: docs

execute:
  execute_notebooks: "off"

launch_buttons:
  thebe: true
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false
